# Generated by Django 2.0.2 on 2019-08-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_link',
            field=models.TextField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
