# Generated by Django 2.0.2 on 2019-08-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video_link',
            field=models.TextField(help_text='Enter a video link if needed', max_length=100, null=True),
        ),
    ]
