# Generated by Django 2.2.4 on 2019-08-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190809_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imgdata',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
