# Generated by Django 2.2.4 on 2019-08-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_post_imgdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imgdata',
            field=models.ImageField(blank=True, upload_to='content'),
        ),
    ]
